### PR TITLE
Change max_redirects to max_redirect to be consistent with LWP::UserAgent

### PR DESCRIPTION
**Pull request by SkySymbol**

### CODE REVIEW

**Comment by kaoru** [comment]
Looking good :-) @evdb do you want to merge this and do a release to CPAN or do you want me to take care of it?

**Comment by evdb** [comment]
All your Alex. Thanks for the improvements Vincent.

**Comment by SkySymbol** [comment]
You're welcome :-)

**Comment by kaoru** [comment]
@SkySymbol HTTP-Async 0.30 with your changes is on its way to CPAN :+1: :smile:

**Pull request merged**
